[server]
headless = true
enableCORS = false
port = 8501

[theme]
base="light"
primaryColor="#4F8BF9"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"
